name: App_automation_a

on:
   workflow_dispatch:
   push:
     branches: 
      - main

# schedule: 
#   - cron : '30 01 * * *'

jobs:
  build:
    runs-on : app_automate_a

      steps:
        - name: Checkout code
             uses: actions/checkout@v4

        - name: install dependencies
          run: | 
            pip install -r requirements.txt

        - name: Run automation tests
          run: |
            pytest -v --html=reports/report.html --self-contained-html

   


