name: App_automation_a

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirement.txt

      - name: Run automation tests
        run: |
          pytest -v --html=reports/report.html --self-contained-html

   


