name: App_automation_a

on:
 push
    branches: 
      - main

schedule: 
  - cron : '30 01 * * *'

jobs:
  build:
    runs-on : annu_app_automation

steps:
  -name: Checkout code
   uses: actions/checkout@v4

  -name: install dependencies
  run: | 
     pip -r install requirements.txt

  - name: Run automation tests
  run: |
      pytest -v --html=reports/report.html --self-contained-html

   


