name: portal_automation_a

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted,app_automation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run automation tests
        run: |

          pytest -v admin.py --html=reports/report.html --self-contained-html

   


